ALTER TABLE STUDENT_REGISTRATION ADD COLUMN REMOTE_REGISTRATION_OID VARCHAR(255);
ALTER TABLE FENIX_DEGREE ADD COLUMN REMOTE_DEGREE_OID VARCHAR(255);
UPDATE STUDENT_REGISTRATION SR INNER JOIN REMOTE_DOMAIN_OBJECT RDO ON SR.OID_REMOTE_REGISTRATION = RDO.OID SET SR.REMOTE_REGISTRATION_OID = RDO.REMOTE_OID;
UPDATE FENIX_DEGREE FD INNER JOIN REMOTE_DOMAIN_OBJECT RDO ON FD.OID_REMOTE_DEGREE = RDO.OID SET FD.REMOTE_DEGREE_OID = RDO.REMOTE_OID;
delete from FF$PERSISTENT_ROOT where OID = 3;
UPDATE FF$PERSISTENT_ROOT set OID_NEXT = 4 where OID = 2;
UPDATE FF$PERSISTENT_ROOT set OID_PREVIOUS = 2 where OID = 4;